R2_ACCOUNT_ID=op://Private/podpiper/R2_ACCOUNT_ID
R2_ACCESS_KEY_ID=op://Private/podpiper/R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY=op://Private/podpiper/R2_SECRET_ACCESS_KEY
HATCHET_CLIENT_TOKEN=op://Private/podpiper/HATCHET_CLIENT_TOKEN
CLOUDFLARE_API_TOKEN=op://Private/podpiper/CLOUDFLARE_API_TOKEN
HATCHET_CLIENT_TLS_STRATEGY=none
