name: temporal
services:
  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d temporal -U temporal"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - SKIP_DYNAMIC_CONFIG_SETUP=true
  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8233:8080"
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8233
      - TEMPORAL_UI_CONTENT_SECURITY_POLICY=
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - temporal-ui
    restart: always

volumes:
  temporal_postgres_data:
